{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "e-gaop.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "e-gaop.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "e-gaop.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "e-gaop.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "e-gaop.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "e-gaop.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "e-gaop.fullname" . }}-app
subjects:
  - kind: ServiceAccount
    name: {{ include "e-gaop.fullname" . }}-app
    namespace: {{ .Release.Namespace }}
{{- end }}
